# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --innodb-log-file-size=100M --innodb-log-files-in-group=2 --max-allowed-packet=30M --bind-address=*
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_USER=$DB_ADMIN_USERNAME
      - MYSQL_ROOT_PASSWORD=$DB_ADMIN_PASSWORD
    volumes:
      - "${DATA_ROOT}/mysql/data:/var/lib/mysql"
    logging:
      driver: json-file

  server:
    image: era-server:latest
    build:
      context: docker-eset-era-server/
    image: era-server:latest
    restart: always
    env_file: .env
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    ports:
      - 2222:2222
    expose:
      - 2223
    volumes:
      - "${DATA_ROOT}/etc:/etc/opt/eset/"
      - "${DATA_ROOT}/var:/var/opt/eset/"
      - "${DATA_ROOT}/log:/var/log/eset/"
    logging:
      driver: json-file

  console:
    image: era-console:latest
    build:
      context: docker-eset-era-console/
    image: era-console:latest
    restart: always
    env_file: .env
    environment:
      - ERA_SRV_HOSTNAME=server
    depends_on:
      - server
#    ports:
#     - 8080:8080
    expose:
      - 8009
    logging:
      driver: json-file

  ajp:
    build: ajp/
    container_name: ajp
    restart: always

    environment:
      - TZ=Asia/Tokyo

    depends_on:
      - console
 
#    expose:
#      - 80
#      - 443

    ports:
      - 80:80
      - 443:443
